# Generated by Django 3.2.25 on 2026-01-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('login_count', models.IntegerField()),
                ('avg_session_time', models.FloatField()),
                ('days_inactive', models.IntegerField()),
                ('feature_usage', models.IntegerField()),
                ('churned', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
